### ISSUE TITLE
fatal error: TH/TH.h: No such file or directory when building dcn_v2

### ISSUE THREAD

**Issue by vslaykovsky** [hrlblab/CircleSnake#1]
I'm getting segfault when using multiple loader workers. Any thoughts on why it's happening?

```
loading annotations into memory...
Done (t=1.45s)
creating index...
index created!
loading annotations into memory...
Done (t=37.37s)
creating index...
index created!
loading annotations into memory...
Done (t=1.01s)
creating index...
index created!
ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
Traceback (most recent call last):
  File "/opt/conda/envs/CircleSnake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/envs/CircleSnake/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/opt/conda/envs/CircleSnake/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/opt/conda/envs/CircleSnake/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/opt/conda/envs/CircleSnake/lib/python3.7/multiprocessing/connection.py", line 921, in wait
    ready = selector.select(timeout)
  File "/opt/conda/envs/CircleSnake/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/opt/conda/envs/CircleSnake/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 14719) is killed by signal: Segmentation fault. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_net.py", line 81, in <module>
    main()
  File "train_net.py", line 76, in main
    train(cfg, network)
  File "train_net.py", line 47, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/home/vslaykovsky/CircleSnake/lib/train/trainers/trainer.py", line 34, in train
    for iteration, batch in enumerate(data_loader):
  File "/opt/conda/envs/CircleSnake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/conda/envs/CircleSnake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/envs/CircleSnake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1152, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/envs/CircleSnake/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1003, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 14719, 14723) exited unexpectedly
```

**Comment by JumingXiong** [comment]
currently, num_workers 0, works for me
